// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Dashboard_Stat
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dashboard_StatMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Dashboard_Stat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Pending("Pending"),
		Running("Running");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dashboard_Stat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Dashboard_Stat"));
	}

	protected Dashboard_Stat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dashboard_StatMendixObject)
	{
		if (dashboard_StatMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Dashboard_Stat", dashboard_StatMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Dashboard_Stat");

		this.dashboard_StatMendixObject = dashboard_StatMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Dashboard_Stat.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Dashboard_Stat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Dashboard_Stat.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Dashboard_Stat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Dashboard_Stat(context, mendixObject);
	}

	public static myfirstmodule.proxies.Dashboard_Stat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Dashboard_Stat.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Dashboard_Stat> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Dashboard_Stat> result = new java.util.ArrayList<myfirstmodule.proxies.Dashboard_Stat>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Dashboard_Stat" + xpathConstraint))
			result.add(myfirstmodule.proxies.Dashboard_Stat.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Pending
	 */
	public final java.lang.Integer getPending()
	{
		return getPending(getContext());
	}

	/**
	 * @param context
	 * @return value of Pending
	 */
	public final java.lang.Integer getPending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pending.toString());
	}

	/**
	 * Set value of Pending
	 * @param pending
	 */
	public final void setPending(java.lang.Integer pending)
	{
		setPending(getContext(), pending);
	}

	/**
	 * Set value of Pending
	 * @param context
	 * @param pending
	 */
	public final void setPending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pending)
	{
		getMendixObject().setValue(context, MemberNames.Pending.toString(), pending);
	}

	/**
	 * @return value of Running
	 */
	public final java.lang.Integer getRunning()
	{
		return getRunning(getContext());
	}

	/**
	 * @param context
	 * @return value of Running
	 */
	public final java.lang.Integer getRunning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Running.toString());
	}

	/**
	 * Set value of Running
	 * @param running
	 */
	public final void setRunning(java.lang.Integer running)
	{
		setRunning(getContext(), running);
	}

	/**
	 * Set value of Running
	 * @param context
	 * @param running
	 */
	public final void setRunning(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer running)
	{
		getMendixObject().setValue(context, MemberNames.Running.toString(), running);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dashboard_StatMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Dashboard_Stat that = (myfirstmodule.proxies.Dashboard_Stat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Dashboard_Stat";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
