// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Stories
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject storiesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Stories";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		Points("Points"),
		Start_Date("Start_Date"),
		Finish_Date("Finish_Date"),
		Status("Status"),
		Stories_Project("MyFirstModule.Stories_Project"),
		Devs_Stories("MyFirstModule.Devs_Stories");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Stories(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Stories"));
	}

	protected Stories(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject storiesMendixObject)
	{
		if (storiesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Stories", storiesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Stories");

		this.storiesMendixObject = storiesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Stories.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Stories initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Stories.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Stories initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Stories(context, mendixObject);
	}

	public static myfirstmodule.proxies.Stories load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Stories.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Stories> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Stories> result = new java.util.ArrayList<myfirstmodule.proxies.Stories>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Stories" + xpathConstraint))
			result.add(myfirstmodule.proxies.Stories.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Points
	 */
	public final java.lang.Integer getPoints()
	{
		return getPoints(getContext());
	}

	/**
	 * @param context
	 * @return value of Points
	 */
	public final java.lang.Integer getPoints(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Points.toString());
	}

	/**
	 * Set value of Points
	 * @param points
	 */
	public final void setPoints(java.lang.Integer points)
	{
		setPoints(getContext(), points);
	}

	/**
	 * Set value of Points
	 * @param context
	 * @param points
	 */
	public final void setPoints(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer points)
	{
		getMendixObject().setValue(context, MemberNames.Points.toString(), points);
	}

	/**
	 * @return value of Start_Date
	 */
	public final java.util.Date getStart_Date()
	{
		return getStart_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Start_Date
	 */
	public final java.util.Date getStart_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Start_Date.toString());
	}

	/**
	 * Set value of Start_Date
	 * @param start_date
	 */
	public final void setStart_Date(java.util.Date start_date)
	{
		setStart_Date(getContext(), start_date);
	}

	/**
	 * Set value of Start_Date
	 * @param context
	 * @param start_date
	 */
	public final void setStart_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date start_date)
	{
		getMendixObject().setValue(context, MemberNames.Start_Date.toString(), start_date);
	}

	/**
	 * @return value of Finish_Date
	 */
	public final java.util.Date getFinish_Date()
	{
		return getFinish_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Finish_Date
	 */
	public final java.util.Date getFinish_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Finish_Date.toString());
	}

	/**
	 * Set value of Finish_Date
	 * @param finish_date
	 */
	public final void setFinish_Date(java.util.Date finish_date)
	{
		setFinish_Date(getContext(), finish_date);
	}

	/**
	 * Set value of Finish_Date
	 * @param context
	 * @param finish_date
	 */
	public final void setFinish_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date finish_date)
	{
		getMendixObject().setValue(context, MemberNames.Finish_Date.toString(), finish_date);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of Stories_Project
	 */
	public final myfirstmodule.proxies.Project getStories_Project() throws com.mendix.core.CoreException
	{
		return getStories_Project(getContext());
	}

	/**
	 * @param context
	 * @return value of Stories_Project
	 */
	public final myfirstmodule.proxies.Project getStories_Project(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Project result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stories_Project.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Project.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Stories_Project
	 * @param stories_project
	 */
	public final void setStories_Project(myfirstmodule.proxies.Project stories_project)
	{
		setStories_Project(getContext(), stories_project);
	}

	/**
	 * Set value of Stories_Project
	 * @param context
	 * @param stories_project
	 */
	public final void setStories_Project(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Project stories_project)
	{
		if (stories_project == null)
			getMendixObject().setValue(context, MemberNames.Stories_Project.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Stories_Project.toString(), stories_project.getMendixObject().getId());
	}

	/**
	 * @return value of Devs_Stories
	 */
	public final java.util.List<myfirstmodule.proxies.Devs> getDevs_Stories() throws com.mendix.core.CoreException
	{
		return getDevs_Stories(getContext());
	}

	/**
	 * @param context
	 * @return value of Devs_Stories
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.Devs> getDevs_Stories(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Devs> result = new java.util.ArrayList<myfirstmodule.proxies.Devs>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Devs_Stories.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.Devs.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Devs_Stories
	 * @param devs_stories
	 */
	public final void setDevs_Stories(java.util.List<myfirstmodule.proxies.Devs> devs_stories)
	{
		setDevs_Stories(getContext(), devs_stories);
	}

	/**
	 * Set value of Devs_Stories
	 * @param context
	 * @param devs_stories
	 */
	public final void setDevs_Stories(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.Devs> devs_stories)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.Devs proxyObject : devs_stories)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Devs_Stories.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return storiesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Stories that = (myfirstmodule.proxies.Stories) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Stories";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
